### ISSUE TITLE
Add TTL and Rate limiting to offer matches

### ISSUE THREAD

**Issue by STAT1C-Sy** [gang-of-fork/p2p-marketplace-backend#42]

**Comment by lumaghg** [comment]
@STAT1C-Sy Hab dich in meine Atlas Org eingeladen dann kannst du das da machen wenn das ohne mongoose nicht im Code geht

**Comment by STAT1C-Sy** [comment]
@lumaghg macht grade keinen Sinn das Rate Limiting reinzumachen das Frontend müsste dann auch das error handling reinbauen das ist jetzt zu kompliziert

**Comment by lumaghg** [comment]
TTL Index für Matches auf 1 Tag ist drin

**Comment by lumaghg** [comment]
@STAT1C-Sy okay dann close ich

**Comment by STAT1C-Sy** [comment]
@lumaghg ist die prod und die dev datenbank die selbe?

**Comment by lumaghg** [comment]
ja

**Comment by STAT1C-Sy** [comment]
ah ok

**Comment by lumaghg** [comment]
gibt nur eine DB

**Comment by lumaghg** [comment]
das geht ja eh nie live

**Comment by lumaghg** [comment]
wegen dezentral

**Comment by STAT1C-Sy** [comment]
ja aber wusste nicht ob du nicht im deployment ne andere db hast
